use crate::ast::*;

pub fn get_all_presets() -> Vec<PresetDecl> {
    vec![
        PresetDecl {
            name: "aviation".into(),
            guards: vec![
                GuardDecl {
                    name: "cabin_temp_C".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: -55.0, max: 70.0 }),
                    priority: Priority::High,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "cabin_pressure_kPa".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 75.0, max: 101.0 }),
                    priority: Priority::Critical,
                    unit: Unit::KPa,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "fuel_flow_pct".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 0.0, max: 100.0 }),
                    priority: Priority::Medium,
                    unit: Unit::Percent,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "hydraulic_pct".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 60.0, max: 100.0 }),
                    priority: Priority::High,
                    unit: Unit::Percent,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "automotive".into(),
            guards: vec![
                GuardDecl {
                    name: "battery_temp".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 15.0, max: 55.0 }),
                    priority: Priority::High,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "brake_pressure".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 0.0, max: 100.0 }),
                    priority: Priority::Critical,
                    unit: Unit::Percent,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "tire_pressure_psi".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 28.0, max: 42.0 }),
                    priority: Priority::Medium,
                    unit: Unit::PSI,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "marine".into(),
            guards: vec![
                GuardDecl {
                    name: "hull_temp".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: -10.0, max: 85.0 }),
                    priority: Priority::Medium,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "sonar_depth".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 0.0, max: 11000.0 }),
                    priority: Priority::High,
                    unit: Unit::Meters,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "medical".into(),
            guards: vec![
                GuardDecl {
                    name: "body_temp".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 35.0, max: 42.0 }),
                    priority: Priority::Critical,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "heart_rate".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 40.0, max: 200.0 }),
                    priority: Priority::Critical,
                    unit: Unit::None,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "spo2_pct".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 90.0, max: 100.0 }),
                    priority: Priority::Critical,
                    unit: Unit::Percent,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "industrial".into(),
            guards: vec![
                GuardDecl {
                    name: "ambient_temp".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: -40.0, max: 85.0 }),
                    priority: Priority::Medium,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "vibration_hz".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 0.0, max: 500.0 }),
                    priority: Priority::High,
                    unit: Unit::None,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "space".into(),
            guards: vec![
                GuardDecl {
                    name: "thermal_range".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: -270.0, max: 150.0 }),
                    priority: Priority::Critical,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "radiation_svh".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 0.0, max: 50.0 }),
                    priority: Priority::Critical,
                    unit: Unit::None,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "nuclear".into(),
            guards: vec![
                GuardDecl {
                    name: "reactor_temp".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 200.0, max: 600.0 }),
                    priority: Priority::Critical,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "coolant_pressure".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 100.0, max: 200.0 }),
                    priority: Priority::Critical,
                    unit: Unit::KPa,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "radiation_level".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 0.0, max: 100.0 }),
                    priority: Priority::Critical,
                    unit: Unit::None,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "robotics".into(),
            guards: vec![
                GuardDecl {
                    name: "joint_temp".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: -20.0, max: 80.0 }),
                    priority: Priority::Medium,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "motor_rpm".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 0.0, max: 3000.0 }),
                    priority: Priority::High,
                    unit: Unit::RPM,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "power_grid".into(),
            guards: vec![
                GuardDecl {
                    name: "voltage".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 200.0, max: 260.0 }),
                    priority: Priority::Critical,
                    unit: Unit::Volts,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "frequency_hz".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 49.0, max: 51.0 }),
                    priority: Priority::Critical,
                    unit: Unit::None,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "load_pct".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: 0.0, max: 95.0 }),
                    priority: Priority::High,
                    unit: Unit::Percent,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
        PresetDecl {
            name: "telecom".into(),
            guards: vec![
                GuardDecl {
                    name: "signal_dbm".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: -120.0, max: -30.0 }),
                    priority: Priority::High,
                    unit: Unit::None,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
                GuardDecl {
                    name: "temp".into(),
                    kind: ConstraintKind::Range(RangeConstraint { min: -40.0, max: 70.0 }),
                    priority: Priority::Medium,
                    unit: Unit::Celsius,
                    temporal: Temporal::None,
                    condition: None,
                    batch_size: None,
                    span: crate::error::Span::zero(),
                },
            ],
            span: crate::error::Span::zero(),
        },
    ]
}
